### ISSUE TITLE
Version conflict with c2cgeoportal 1.6.x

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#267]
We have a serious version conflict since the version of pyramid was fixed to 1.9.1 in this project. We are not able any longer to install the pyramid_oereb project along side the c2c geoportal 1.6.8 for instance.

From our point of view it is not necessary to fix the pyramid version that much. Do you see a way to lose it a little?

**Comment by sbrunner** [comment]
I don't think that's a good idea to put two pyramid applications in the same venv I suggest to have to separate WSGI application and venv.

**Comment by vvmruder** [comment]
Sorry Stephane. There I need to hook in with a strict: NO!
The plan was always and is still to have a pyramid **plugin** for pyramid_oereb. Exactly for the case to be able to run it in an existing pyramid application. This was the deal.

**Comment by vvmruder** [comment]
All other stuff should be solved in a separate project which integrates this plugin. So this -lets call it meta project- should be the point for "separate WSGI application and venv"

**Comment by vvmruder** [comment]
Or maybe I have misunderstood your answer?

**Comment by sbrunner** [comment]
I think that you understand, and for me it's a good practice to separate the booth application, also to have different live-cycle...

So, does something like this https://github.com/camptocamp/pyramid_oereb/compare/versions will solve your issue?

**Comment by vvmruder** [comment]
A comment to the first paragraph: We clearly have many python eggs (even pyramid plugins) which are having a own life cycle but are working together. This was the plan for this pyramid_oereb project too. There is absolutely no reason to set pyramid_oereb's dependency that much to pyramid because it is made to work with manly every version (with some side notes... but it will). Therefore I do really not understand why the plan is now to separate this small lib/plugin into a dedicated pyramid application. We have a real misunderstanding of our code here if you really provide this as a roadmap for this project...

**Comment by vvmruder** [comment]
To your suggestion: Yes, this should work.

**Comment by vvmruder** [comment]
One question in addition: Do you mean "separate the both application" or do you really mean "separate the booth application"?
If the second: What does it mean for you?

**Comment by sbrunner** [comment]
For schwyz I create a small independent project here: https://github.com/camptocamp/schwyz_oereb
Then He can live hes life, on the same server as GeoMapFish :-)

**Comment by vvmruder** [comment]
Ok. This is exactly how I meant it. So we are on the same way now :) Glad for that.

**Comment by jwkaltz** [comment]
In my understanding, the changes that resulted consequently to this issue are not practicable.

The newest geolink_formatter version is 1.2.0, but this is not compatible with pyramid_oereb (yet), instead, version 1.1.2 should be used, but it is not used (because our setup.py now throws out the version numbers). So if somebody (e.g., me...) builds an application using pyramid_oereb, it will always use the newest versions of all dependencies. 

This means IIUC we can never be sure that pyramid_oereb is functional when built (or rebuilt), neither in its master nor in older versions, because a situation such as for geolink_formatter can happen at any time, with any of the dependencies.

**Comment by jwkaltz** [comment]
Note also that currently, the requires.io dependency update mechanism is useless (and even misleading), since we ignore the versions. Furthermore, if we do keep this setup, we should remove the versions from requirements.txt, and instead define the required dependencies of pyramid_oereb within each project that uses pyramid_oereb (not my preferred solution, but better than the current situation).

**Comment by jwkaltz** [comment]
We discussed this with @sbrunner and @ger-benjamin . We still recommend running pyramid_oereb in its own application container. The current situation regarding dependencies is not good. However, we should still be more flexible with versioning than what we were up to the change made on october 4th. When using pyramid_oereb in a container application, the build process should be able to install the recommended versions of the libraries needed by pyramid_oereb, but not force these versions. 
I will open a new issue for that.
