### ISSUE TITLE
Spatial relation for calculation

### ISSUE THREAD

**Issue by kdeininger** [camptocamp/pyramid_oereb#383]
Until now, we use `intersects` to query the candidates and decide between inside and outside restrictions. This spatial relation also returns touching elements, but we don't need them for the extract. We even dismiss small intersections.

Maybe it would be better to use a combination of `overlaps` and `contains` to improve the processing performance.

**Comment by vvmruder** [comment]
Good idea. This will be a good change for next version?

**Comment by vvmruder** [comment]
It pointed out, that we had a missleading idea of using intersect when we used "intersect" for every geometry type.

See this example:
![grafik](https://user-images.githubusercontent.com/3714179/35321108-70e499ae-00e6-11e8-953b-52d815e59e42.png)


The parcel is intersecting with "Hecken, Feldgehölze" which is a polygon. Since it only shares points with the parcel the "intersects" operation is finding this. Later in the logic  the found element is really intersected with real estate. This gives a line as result. Thats why the symbology delivers a polygon symbol for a line of the length of 257m.

We will work on that to fix it.

**Comment by vvmruder** [comment]
More input appreciated

**Comment by vvmruder** [comment]
@jwkaltz can you confirm: I understood you like you think there should be a more detailed logging?

Especially for demystifying intersection and later following filter process I will include a more extensive logging.

**Comment by vvmruder** [comment]
We will close this issue.
