### ISSUE TITLE
Add all official translations in pyramid_oereb.yml.mako

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#460]
I suggest that we add the official translations in the standard.yaml (https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/standard/pyramid_oereb.yml.mako) where they are defined in the specs, like the topic titles as an example : Contaminated sites = Belastete Standorte = Sites pollués

**Comment by vvmruder** [comment]
👍 It should be already available on each plr configurations "text" attribute. It needs only to be filled up with the correct translation. Am I right?

**Comment by pfirpfel** [comment]
@vvmruder Is there a good reference for these translations?
I started using these [XML code lists from 2017](http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V1_1_Codelisten_20170101.xml), but some translations don't seem right.
For example AirportsSecurityZonePlans don't have the airport itself in the title ('Safety zone plan' instead of 'Airport safety zone plan').

**Comment by pfirpfel** [comment]
Also ping @voisardf

**Comment by peterschaer** [comment]
We should use the mentionned XML code lists. They are the official topic titles drawn from the [GeoIV](https://www.admin.ch/opc/de/classified-compilation/20071088/index.html).

**Comment by voisardf** [comment]
best would be to use the official translations from https://www.termdat.bk.admin.ch/Search/Search
Keyword for the PLR translations collection is OERB16
