### ISSUE TITLE
inconsistent application status if first request fails

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#681]
When pyramid_oereb is included in a wsgi application and if the first request fails due to for example a database error, subsequent requests fail due to another error (even if the original database error is fixed):
`...   File ".../.venv/lib/python2.7/site-packages/pyramid_oereb/__init__.py", line 63, in includeme
... Config.init(cfg_file or cfg_c2ctemplate_file, cfg_section, cfg_file is None)
... File ".../.venv/lib/python2.7/site-packages/pyramid_oereb/lib/config.py", line 87, in init
... assert Config._config is None
... AssertionError
`
There seems to be something inconsistent about the application status in this case. In the first request, the configuration was partially read, but not completely (due to the error), but pyramid_oereb considers that is has been fully read.

**Comment by jwkaltz** [comment]
To be reevaluated after PR #736 (that PR might solve this problem, too)

**Comment by ger-benjamin** [comment]
Step to reproduce:
```
  0. (prerequisite) do something bad to database, for example rename an oereb table
  1. apache graceful
  2. do versions request (for example) -> in log, you see error because of missing database table
  3. rename the oereb database table to the right name -> now everything should work, right?
  4. do versions request (for example) -> in log, you see Config is not none error
```

--> Analyze:
- At step 2: init can initialize the Config (singleton), but fail to create the processor (because the db is called). So the init fail before to finish
- At step 3: the init is done again (because it has failed) but the config is already initialized -> init fail.

The processor must be initialized later. It must not make the init fail. We won't do the init multiple times.
